-- Run these commands as ACCOUNTADMIN to set up proper permissions for dbt

-- Switch to admin role
USE ROLE ACCOUNTADMIN;

-- Create database if it doesn't exist
CREATE DATABASE IF NOT EXISTS SKELLO_INTERCOM;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS SKELLO_INTERCOM.RAW;
CREATE SCHEMA IF NOT EXISTS SKELLO_INTERCOM.STG;
CREATE SCHEMA IF NOT EXISTS SKELLO_INTERCOM.MART;

-- Create dbt role if it doesn't exist
CREATE ROLE IF NOT EXISTS DBT_ROLE;

-- Grant database-level permissions
GRANT USAGE ON DATABASE SKELLO_INTERCOM TO ROLE DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE SKELLO_INTERCOM TO ROLE DBT_ROLE;

-- Grant schema-level permissions
GRANT USAGE ON SCHEMA SKELLO_INTERCOM.RAW TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA SKELLO_INTERCOM.STG TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA SKELLO_INTERCOM.MART TO ROLE DBT_ROLE;

-- Grant full permissions on target schemas (where dbt creates models)
GRANT ALL ON SCHEMA SKELLO_INTERCOM.STG TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA SKELLO_INTERCOM.MART TO ROLE DBT_ROLE;

-- Grant read permissions on raw data
GRANT SELECT ON ALL TABLES IN SCHEMA SKELLO_INTERCOM.RAW TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SKELLO_INTERCOM.RAW TO ROLE DBT_ROLE;

-- Grant warehouse usage (adjust warehouse name as needed)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_ROLE;

-- Assign role to user (replace YOUR_USERNAME with actual username)
-- GRANT ROLE DBT_ROLE TO USER YOUR_USERNAME;

COMMIT;